default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: instabug-dev

test:
  <<: *default
  database: instabug-test

production:
  <<: *default
  database: instabug
